### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by valasek** [yusufkandemir/quasarian-in-action-helper#4]
Steps to reproduce on master:
`./bin/parse-issues -d=15`

or merge https://github.com/yusufkandemir/quasarian-in-action-helper/pull/3 and run
`./bin/parse-issues`

**Error**
``` bash
./bin/parse-issues
(node:23658) UnhandledPromiseRejectionWarning: TypeError: rawIssues.filter is not a function
    at parseIssues (/home/valasek/Programming/quasarian-in-action-helper/src/parse.js:18:6)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:23658) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:23658) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by yusufkandemir** [comment]
That is probably happening because of Github API rate limits. You need to follow [this](https://github.com/yusufkandemir/quasarian-in-action-helper#increase-github-api-rate-limit-optional) to get an access key. I will send a PR that adds proper error handling, the issue will become clearly understandable.
